on:
  workflow_dispatch:
jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - run: echo "step 0"
      - run: echo "step 1"
      - run: echo "step 2"
      - run: echo "step 3"
      - run: echo "step 4"
      - run: echo "step 5"
      - run: echo "step 6"
      - run: echo "step 7"
      - run: echo "step 8"
      - run: echo "step 9"
      - run: echo "step 10"
      - run: echo "step 11"
      - run: echo "step 12"
      - run: echo "step 13"
      - run: echo "step 14"
      - run: echo "step 15"
      - run: echo "step 16"
      - run: echo "step 17"
      - run: echo "step 18"
      - run: echo "step 19"
      - run: echo "step 20"
      - run: echo "step 21"
      - run: echo "step 22"
      - run: echo "step 23"
      - run: echo "step 24"
      - run: echo "step 25"
      - run: echo "step 26"
      - run: echo "step 27"
      - run: echo "step 28"
      - run: echo "step 29"
      - run: echo "step 30"
      - run: echo "step 31"
      - run: echo "step 32"
      - run: echo "step 33"
      - run: echo "step 34"
      - run: echo "step 35"
      - run: echo "step 36"
      - run: echo "step 37"
      - run: echo "step 38"
      - run: echo "step 39"
      - run: echo "step 40"
      - run: echo "step 41"
      - run: echo "step 42"
      - run: echo "step 43"
      - run: echo "step 44"
      - run: echo "step 45"
      - run: echo "step 46"
      - run: echo "step 47"
      - run: echo "step 48"
      - run: echo "step 49"