on:
  workflow_dispatch:
jobs:
  j:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: hyper-2
          fetch-depth: 1
      - uses: actions/upload-artifact@v4
        with:
          name: foo
          path: out/
